using UnityEngine;

namespace AeroTerra.Core
{
    /// <summary>
    /// A flyable real-world area. Instances are data assets generated by ProjectBootstrap
    /// under Assets/Resources/Maps/ — externalized config, not hardcoded C#: edit spawn
    /// position/heading (or any other field) directly on the .asset in the Inspector, or
    /// add a brand new city by creating another "AeroTerra/Map Definition" asset there.
    /// No code changes or rebuild needed for either.
    /// </summary>
    [CreateAssetMenu(menuName = "AeroTerra/Map Definition", fileName = "MapDef")]
    public class MapDefinition : ScriptableObject
    {
        [Header("Identity")]
        public string Id;
        public string DisplayName;
        public string Country;
        [TextArea] public string Description;

        [Header("Starting position")]
        public double Latitude;
        public double Longitude;
        public double SpawnAltitudeMeters = 150;
        public float SpawnHeadingDeg = 0f; // yaw at spawn, 0 = north

        private static MapDefinition[] _all;

        /// <summary>Every map asset under Resources/Maps, loaded once and cached.</summary>
        public static MapDefinition[] All
        {
            get
            {
                if (_all == null) _all = Resources.LoadAll<MapDefinition>("Maps");
                return _all;
            }
        }

        /// <summary>Fallback map when none is selected (e.g. Flight scene opened directly).</summary>
        public static MapDefinition Default
        {
            get
            {
                var maps = All;
                foreach (var m in maps) if (m.Id == "london") return m;
                return maps.Length > 0 ? maps[0] : null;
            }
        }
    }
}
