using UnityEngine;

namespace AeroTerra.Core
{
    /// <summary>
    /// A flyable real-world area. Instances are data assets generated by ProjectBootstrap
    /// under Assets/Resources/Maps/ — externalized config, not hardcoded C#: edit spawn
    /// position/heading (or any other field) directly on the .asset in the Inspector, or
    /// add a brand new city by creating another "AeroTerra/Map Definition" asset there.
    /// No code changes or rebuild needed for either.
    /// </summary>
    [CreateAssetMenu(menuName = "AeroTerra/Map Definition", fileName = "MapDef")]
    public class MapDefinition : ScriptableObject
    {
        [Header("Identity")]
        public string Id;
        public string DisplayName;
        public string Country;
        [TextArea] public string Description;

        [Header("Starting position")]
        public double Latitude;
        public double Longitude;
        public double SpawnAltitudeMeters = 150;
        public float SpawnHeadingDeg = 0f; // yaw at spawn, 0 = north

        /// <summary>Named real-world points shown as bearing markers on the Flight HUD's
        /// NAV minimap (see FlightHUD.BuildMinimap) — purely flavor/orientation data, not
        /// tied to any Cesium tileset metadata (none is queryable at runtime; see
        /// FlatOffsetMeters below). Populated by ProjectBootstrap.CreateMaps for the stock
        /// cities; add more directly on the .asset in the Inspector for any map.</summary>
        [System.Serializable]
        public class Landmark
        {
            public string Name;
            public double Latitude;
            public double Longitude;
        }

        [Header("Minimap landmarks")]
        public Landmark[] Landmarks = System.Array.Empty<Landmark>();

        /// <summary>Named, selectable spawn presets for this map (Settings ▸ Free Flight ▸
        /// Flying Conditions ▸ SPAWN LOCATION tab) — unlike Landmark above, each one is a
        /// real place the drone can actually launch from: a description of the challenge
        /// it sets up and its own recommended spawn altitude. Picking one overrides the
        /// map's own Latitude/Longitude (via FlatOffsetMeters, same flat-earth conversion
        /// Landmarks/the minimap already use) for that flight only — see
        /// GameManager.SelectedSpawnLocationOverride. Populated by ProjectBootstrap for the
        /// stock cities; add more directly on the .asset in the Inspector for any map.</summary>
        [System.Serializable]
        public class SpawnLocation
        {
            public string Name;
            public double Latitude;
            public double Longitude;
            [TextArea] public string Description;
            public double SpawnAltitudeMeters = 150;
        }

        [Header("Spawn location presets")]
        public SpawnLocation[] SpawnLocations = System.Array.Empty<SpawnLocation>();

        /// <summary>Flat-earth local-tangent-plane approximation of a (lat,lon) point's
        /// offset in meters from (originLat,originLon) — (+x = east, +y = north). Accurate
        /// to well within HUD-minimap tolerances at the few-kilometer distances landmarks
        /// sit at; matches the same simplification Cesium's own georeference uses for the
        /// flat Unity world X/Z near the origin (see MapManager.BuildWorld), so it lines up
        /// with the HOME marker's existing "world XZ ≈ meters from origin" convention.</summary>
        public static Vector2 FlatOffsetMeters(double lat, double lon, double originLat, double originLon)
        {
            const double metersPerDegLat = 111320.0;
            double metersPerDegLon = metersPerDegLat * System.Math.Cos(originLat * System.Math.PI / 180.0);
            float east = (float)((lon - originLon) * metersPerDegLon);
            float north = (float)((lat - originLat) * metersPerDegLat);
            return new Vector2(east, north);
        }

        private static MapDefinition[] _all;

        /// <summary>Every map asset under Resources/Maps, loaded once and cached.</summary>
        public static MapDefinition[] All
        {
            get
            {
                if (_all == null) _all = Resources.LoadAll<MapDefinition>("Maps");
                return _all;
            }
        }

        /// <summary>Fallback map when none is selected (e.g. Flight scene opened directly).</summary>
        public static MapDefinition Default
        {
            get
            {
                var maps = All;
                foreach (var m in maps) if (m.Id == "london") return m;
                return maps.Length > 0 ? maps[0] : null;
            }
        }
    }
}
